server:
  port: 7777

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/matchingdb
    username: root
    password: pjsy389527@@

  jpa:
    database-platform:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug
